### ISSUE TITLE
health_checks.py little bug

### ISSUE THREAD

**Issue by hetian127** [imbue-ai/cluster-health#3]
running the python scripts, error:
![image](https://github.com/user-attachments/assets/0ef4eea4-0996-4aa9-b8be-71ef1b4ce156)

exchange the blow two lines, it works
![image](https://github.com/user-attachments/assets/85458b16-7fec-4353-bca7-8615d930fda0)

**Comment by bawr** [comment]
Oh, thanks - the published version is missing a sort we use internally, we'll fix it here in a bit.
